<?php
declare(strict_types=1);
namespace App\Service;
use App\Exception\AuthException;
use Hyperf\Contract\IdGeneratorInterface;
use Hyperf\Database\ConnectionInterface;
use Hyperf\DbConnection\Db;
/** 管理采购方应用凭据、API 订阅及供应商配额。 */
final class ApplicationService
{
 /** 初始化当前组件所需的依赖。 */
 public function __construct(private Db $db,private IdGeneratorInterface $ids){}
 /** 校验输入并创建业务记录。 @return array{application_id:int,secret:string} */
 public function create(int $buyerId,string $name):array{$name=trim($name);if($buyerId<=0||$name===''||mb_strlen($name)>128)throw AuthException::badRequest('应用名称无效。');return $this->db->transaction(function(ConnectionInterface$c)use($buyerId,$name):array{$app=$this->ids->generate();$cred=$this->ids->generate();$prefix='ak_'.bin2hex(random_bytes(6));$secret='app_live_'.$prefix.'.'.bin2hex(random_bytes(32));$c->insert('INSERT INTO `buyer_applications` (`id`,`buyer_profile_id`,`name`,`status`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,\'active\',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL)',[$app,$buyerId,$name]);$c->insert('INSERT INTO `application_credentials` (`id`,`application_id`,`secret_hash`,`key_prefix`,`status`,`revoked_at`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,\'active\',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL)',[$cred,$app,hash('sha256',$secret),$prefix]);return['application_id'=>$app,'secret'=>$secret];});}
 /** 更新 `updateQuota` 方法对应的数据或业务状态。 */
 public function updateQuota(int $supplierId,int $subscriptionId,int $qps,int $period):void{if($qps<1||$qps>100000||$period<1)throw AuthException::badRequest('额度无效。');$this->db->transaction(function(ConnectionInterface$c)use($supplierId,$subscriptionId,$qps,$period):void{$old=$c->selectOne('SELECT q.`id`,q.`qps_limit`,q.`period_limit` FROM `subscription_quotas` q INNER JOIN `api_subscriptions` s ON s.`id`=q.`subscription_id` WHERE q.`subscription_id`=? AND s.`supplier_profile_id`=? AND q.`deleted_at` IS NULL AND s.`deleted_at` IS NULL LIMIT 1 FOR UPDATE',[$subscriptionId,$supplierId]);if(!is_object($old))throw AuthException::badRequest('订阅额度不存在。');$c->update('UPDATE `subscription_quotas` SET `qps_limit`=?,`period_limit`=?,`config_version`=`config_version`+1,`updated_at`=CURRENT_TIMESTAMP WHERE `id`=?',[$qps,$period,(int)$old->id]);$c->insert('INSERT INTO `quota_audit_logs` (`id`,`supplier_profile_id`,`subscription_id`,`old_qps_limit`,`new_qps_limit`,`old_period_limit`,`new_period_limit`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL)',[$this->ids->generate(),$supplierId,$subscriptionId,(int)$old->qps_limit,$qps,(int)$old->period_limit,$period]);});}
 /** 查询采购方的应用列表。 @return list<array<string,mixed>> */
public function applications(int$buyerId):array{return$this->rows($this->db->select('SELECT `id`,`name`,`status`,`created_at` FROM `buyer_applications` WHERE `buyer_profile_id`=? AND `deleted_at` IS NULL ORDER BY `created_at` DESC',[$buyerId]));}
 /** 查询采购方的 API 订阅列表。 @return list<array<string,mixed>> */
public function subscriptions(int$buyerId):array{return$this->rows($this->db->select('SELECT s.`id`,a.`name` AS `application_name`,p.`name` AS `api_name`,v.`version`,s.`status`,q.`qps_limit`,q.`period_limit` FROM `api_subscriptions` s INNER JOIN `buyer_applications` a ON a.`id`=s.`application_id` INNER JOIN `api_products` p ON p.`id`=s.`api_product_id` INNER JOIN `api_versions` v ON v.`id`=s.`api_version_id` INNER JOIN `subscription_quotas` q ON q.`subscription_id`=s.`id` AND q.`deleted_at` IS NULL WHERE a.`buyer_profile_id`=? AND s.`deleted_at` IS NULL ORDER BY s.`created_at` DESC',[$buyerId]));}
 /** 执行 `supplierQuotas` 方法对应的业务处理。 @return list<array<string,mixed>> */
public function supplierQuotas(int$supplierId):array{return$this->rows($this->db->select('SELECT s.`id` AS `subscription_id`,a.`name` AS `application_name`,p.`name` AS `api_name`,q.`qps_limit`,q.`period_limit`,q.`config_version` FROM `api_subscriptions` s INNER JOIN `buyer_applications` a ON a.`id`=s.`application_id` INNER JOIN `api_products` p ON p.`id`=s.`api_product_id` INNER JOIN `subscription_quotas` q ON q.`subscription_id`=s.`id` AND q.`deleted_at` IS NULL WHERE s.`supplier_profile_id`=? AND s.`deleted_at` IS NULL ORDER BY s.`created_at` DESC',[$supplierId]));}
 /** 执行 `subscribe` 方法对应的业务处理。 */
 public function subscribe(int$buyerId,int$appId,int$productId):void{$this->db->transaction(function(ConnectionInterface$c)use($buyerId,$appId,$productId):void{$app=$c->selectOne('SELECT `id` FROM `buyer_applications` WHERE `id`=? AND `buyer_profile_id`=? AND `status`=\'active\' AND `deleted_at` IS NULL LIMIT 1 FOR UPDATE',[$appId,$buyerId]);$product=$c->selectOne('SELECT `current_published_version_id`,`supplier_profile_id` FROM `api_products` WHERE `id`=? AND `status`=\'published\' AND `deleted_at` IS NULL LIMIT 1',[$productId]);if($app===null||!is_object($product))throw AuthException::badRequest('应用或 API 不可用。');$subscription=$this->ids->generate();$quota=$this->ids->generate();$c->insert('INSERT INTO `api_subscriptions` (`id`,`application_id`,`api_product_id`,`api_version_id`,`supplier_profile_id`,`status`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,?,\'active\',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL)',[$subscription,$appId,$productId,(int)$product->current_published_version_id,(int)$product->supplier_profile_id]);$c->insert('INSERT INTO `subscription_quotas` (`id`,`subscription_id`,`qps_limit`,`period_limit`,`period_seconds`,`config_version`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,10,100000,2592000,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL)',[$quota,$subscription]);});}
 /** 重置 `resetSecret` 方法对应的数据或业务状态。 @return array{secret:string} */
public function resetSecret(int$buyerId,int$appId):array{return$this->db->transaction(function(ConnectionInterface$c)use($buyerId,$appId):array{if($c->selectOne('SELECT `id` FROM `buyer_applications` WHERE `id`=? AND `buyer_profile_id`=? AND `deleted_at` IS NULL LIMIT 1 FOR UPDATE',[$appId,$buyerId])===null)throw AuthException::badRequest('应用不存在。');$c->update('UPDATE `application_credentials` SET `status`=\'revoked\',`revoked_at`=CURRENT_TIMESTAMP,`updated_at`=CURRENT_TIMESTAMP WHERE `application_id`=? AND `status`=\'active\' AND `deleted_at` IS NULL',[$appId]);$prefix='ak_'.bin2hex(random_bytes(6));$secret='app_live_'.$prefix.'.'.bin2hex(random_bytes(32));$c->insert('INSERT INTO `application_credentials` (`id`,`application_id`,`secret_hash`,`key_prefix`,`status`,`revoked_at`,`created_at`,`updated_at`,`deleted_at`) VALUES (?,?,?,?,\'active\',NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL)',[$this->ids->generate(),$appId,hash('sha256',$secret),$prefix]);return['secret'=>$secret];});}
 /** 撤销 `revokeSecret` 方法对应的数据或业务状态。 */
 public function revokeSecret(int$buyerId,int$appId):void{if($this->db->update('UPDATE `application_credentials` c INNER JOIN `buyer_applications` a ON a.`id`=c.`application_id` SET c.`status`=\'revoked\',c.`revoked_at`=CURRENT_TIMESTAMP,c.`updated_at`=CURRENT_TIMESTAMP WHERE c.`application_id`=? AND a.`buyer_profile_id`=? AND c.`status`=\'active\' AND c.`deleted_at` IS NULL AND a.`deleted_at` IS NULL',[$appId,$buyerId])<1)throw AuthException::badRequest('有效密钥不存在。');}
 /** 把数据库查询结果统一转换为数组列表。 @param list<object|array<string,mixed>>$rows @return list<array<string,mixed>> */
private function rows(array$rows):array{return array_map(static fn(object|array$r):array=>is_object($r)?get_object_vars($r):$r,$rows);}
}
