<?php
declare(strict_types=1);namespace App\Service;use Hyperf\DbConnection\Db;
/** 维护账单、账单项、付款凭证、佣金、结算与审计的数据结构。 */
final class BillingSchemaService{public function __construct(private Db$db){}public function ensureSchema():void{foreach([
"CREATE TABLE IF NOT EXISTS `billing_invoices` (`id` BIGINT UNSIGNED NOT NULL,`buyer_profile_id` BIGINT UNSIGNED NOT NULL,`period_id` VARCHAR(32) NOT NULL,`status` VARCHAR(24) NOT NULL DEFAULT 'issued',`total_micros` BIGINT UNSIGNED NOT NULL,`issued_at` TIMESTAMP NULL DEFAULT NULL,`due_at` TIMESTAMP NULL DEFAULT NULL,`grace_until` TIMESTAMP NULL DEFAULT NULL,`paid_at` TIMESTAMP NULL DEFAULT NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY(`id`),UNIQUE KEY `uniq_buyer_period_invoice`(`buyer_profile_id`,`period_id`),KEY `idx_invoice_due`(`status`,`grace_until`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS `billing_items` (`id` BIGINT UNSIGNED NOT NULL,`invoice_id` BIGINT UNSIGNED NOT NULL,`subscription_id` BIGINT UNSIGNED NOT NULL,`supplier_profile_id` BIGINT UNSIGNED NOT NULL,`call_count` BIGINT UNSIGNED NOT NULL,`unit_price_micros` BIGINT UNSIGNED NOT NULL,`gross_micros` BIGINT UNSIGNED NOT NULL,`commission_bps` INT UNSIGNED NOT NULL,`commission_micros` BIGINT UNSIGNED NOT NULL,`supplier_net_micros` BIGINT UNSIGNED NOT NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY(`id`),UNIQUE KEY `uniq_invoice_subscription`(`invoice_id`,`subscription_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS `payment_proofs` (`id` BIGINT UNSIGNED NOT NULL,`invoice_id` BIGINT UNSIGNED NOT NULL,`reference_no` VARCHAR(128) NOT NULL,`proof_path` VARCHAR(512) NOT NULL,`status` VARCHAR(24) NOT NULL DEFAULT 'pending',`reviewed_by_admin_id` BIGINT UNSIGNED NULL,`reviewed_at` TIMESTAMP NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY(`id`),KEY `idx_payment_review`(`status`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS `commission_configs` (`id` BIGINT UNSIGNED NOT NULL,`supplier_profile_id` BIGINT UNSIGNED NOT NULL,`commission_bps` INT UNSIGNED NOT NULL,`status` VARCHAR(16) NOT NULL DEFAULT 'active',`effective_at` TIMESTAMP NULL DEFAULT NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY(`id`),KEY `idx_commission_effective`(`supplier_profile_id`,`status`,`effective_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS `supplier_settlements` (`id` BIGINT UNSIGNED NOT NULL,`supplier_profile_id` BIGINT UNSIGNED NOT NULL,`period_id` VARCHAR(32) NOT NULL,`gross_micros` BIGINT UNSIGNED NOT NULL,`commission_micros` BIGINT UNSIGNED NOT NULL,`net_micros` BIGINT UNSIGNED NOT NULL,`status` VARCHAR(24) NOT NULL DEFAULT 'pending',`confirmed_by_admin_id` BIGINT UNSIGNED NULL,`confirmed_at` TIMESTAMP NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY(`id`),UNIQUE KEY `uniq_supplier_period_settlement`(`supplier_profile_id`,`period_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS `billing_audit_logs` (`id` BIGINT UNSIGNED NOT NULL,`actor_admin_id` BIGINT UNSIGNED NULL,`action` VARCHAR(64) NOT NULL,`target_type` VARCHAR(32) NOT NULL,`target_id` BIGINT UNSIGNED NOT NULL,`summary` JSON NULL,`created_at` TIMESTAMP NULL,`updated_at` TIMESTAMP NULL,`deleted_at` TIMESTAMP NULL,PRIMARY KEY(`id`),KEY `idx_billing_audit_target`(`target_type`,`target_id`,`created_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"]as$sql)$this->db->statement($sql);}}
